services:

  flask-app:
    container_name: flask_app
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - DB_URL=postgresql://admin:root@db:5432/jail_db
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jail_db
